# Generated by Django 2.2.24 on 2021-08-20 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_criacao',
            new_name='data_criado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_publicao',
            new_name='data_publicado',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
